version: "3"
services:
  web:
    build: .
    image: nargyanti/latihan-quiz2-cloud:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html